[build]
base = "dist/angular"

[functions]
directory = 'netlify/functions'

[[redirects]]
from = "/api/"
to = "/.netlify/funtcions/"
status = 200

[dev]
  command = "yarn start"
  port = 8888
  publish = "dist/angular"